Initial Commit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,8 +32,12 @@ jobs:
         id: build_app
         run: |
           set -euo pipefail
-          mvn clean package --batch-mode --no-transfer-progress
-        shell: bash
+          mvn clean package --batch-mode --no-transfer-progress 2> build_error.log || {
+          echo "error_message<<EOF" >> $GITHUB_OUTPUT
+          tail -n 50 build_error.log >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+          exit 1
+          }
 
       - name: Run Tests
         if: success()  
@@ -56,7 +60,7 @@ jobs:
         with:
           payload: |
             {
-              "text": ":x: Maven Build Failed for *${{ github.repository }}*\n> *Commit*: `${{ github.sha }}` - _${{ github.event.head_commit.message }}_\n> *Author*: ${{ github.actor }}\n> *Run*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              "text": ":x: Maven Build Failed for *${{ github.repository }}*\n> *Commit*: `${{ github.sha }}` - _${{ github.event.head_commit.message }}_\n> *Author*: ${{ github.actor }}\n> *Run*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\n>*Error Snippet:*```${{ steps.build_app.outputs.error_message }}```",
               "channel": "#build-notifications"
             }
         env:
