Workflow Updated

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,22 +45,22 @@ jobs:
           mvn clean package --file "${{ github.event.inputs.pom_path }}" --batch-mode --no-transfer-progress > build_output.log 2>&1
           BUILD_STATUS=$?
           echo "::group::Maven Output (tail)"
-          tail -n 90 build_output.log || echo "No output file"
+          tail -n 50 build_output.log || echo "No output file"
           echo "::endgroup::"
           if [ $BUILD_STATUS -ne 0 ]; then
             echo "Build failed, capturing logs..."
-            tail -n 90 build_output.log | tr '\n' ' ' | sed 's/"/\\"/g' > error.log
+            tail -n 50 build_output.log | tr '\n' ' ' | sed 's/"/\\"/g' > error.log
             ERROR_MSG=$(cat error.log)
             echo "error_message=$ERROR_MSG" >> "$GITHUB_OUTPUT"
           fi
           exit $BUILD_STATUS
         shell: bash
 
-      # - name: Show Error Message Output
-      #   if: failure()
-      #   run: |
-      #     echo "Captured Error Output:"
-      #     echo "${{ steps.build_app.outputs.error_message }}"
+      - name: Show Error Message Output
+        if: failure()
+        run: |
+          echo "Captured Error Output:"
+          echo "${{ steps.build_app.outputs.error_message }}"
       
       - name: Upload Error Log File
         if: failure()
